name: Deploy API

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Deploy to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: tweeter
                  entrypoint: index.ts
                  root: apps/api
